/c footy_db;

-- DROP TABLES

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS leagues CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS coaches CASCADE;
DROP TABLE IF EXISTS users_leagues CASCADE;
DROP TABLE IF EXISTS users_teams CASCADE;
DROP TABLE IF EXISTS countries_leagues CASCADE;
DROP TABLE IF EXISTS leagues_teams CASCADE;
DROP TABLE IF EXISTS teams_players CASCADE;
DROP TABLE IF EXISTS teams_coaches CASCADE;

-- CREATE TABLES
 
CREATE TABLE users
(
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE countries
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  flag TEXT NOT NULL
);

CREATE TABLE leagues
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  api_football_id INTEGER NOT NULL
);

CREATE TABLE teams
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  api_football_id INTEGER
);

CREATE TABLE players
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  nationality TEXT,
  api_football_id INTEGER
);

CREATE TABLE coaches
(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  nationality TEXT
);

-- JOIN TABLES

CREATE TABLE users_leagues
(id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  league_id INTEGER REFERENCES leagues (id) ON DELETE CASCADE
);

CREATE TABLE users_teams
(id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  team_id INTEGER REFERENCES teams (id) ON DELETE CASCADE
);

CREATE TABLE countries_leagues
(
  id SERIAL PRIMARY KEY,
  country_id INTEGER REFERENCES countries (id) ON DELETE CASCADE,
  league_id INTEGER REFERENCES leagues (id) ON DELETE CASCADE
);

CREATE TABLE leaugues_teams
(
  id SERIAL PRIMARY KEY,
  league_id INTEGER REFERENCES leagues (id) ON DELETE CASCADE,
  team_id INTEGER REFERENCES teams (id) ON DELETE CASCADE
);

CREATE TABlE teams_players
(
  id SERIAL PRIMARY KEY,
  team_id INTEGER REFERENCES teams (id) ON DELETE CASCADE,
  player_id INTEGER REFERENCES players (id) ON DELETE CASCADE
);

CREATE TABLE teams_coaches
(
  id SERIAL PRIMARY KEY,
  team_id INTEGER REFERENCES teams (id) ON DELETE CASCADE,
  coach_id INTEGER REFERENCES coaches (id) ON DELETE CASCADE
);