const INTERNATIONAL_COMPS = [
	`FIFA World Cup`,
	`FIFA Confederations Cup`,
	`FIFA World Cup Qualifying - UEFA`,
	`FIFA World Cup Qualifying - AFC`,
	`FIFA World Cup Qualifying - OFC`,
	`FIFA Under-17 World Cup`,
	`CONCACAF Nations League`,
	`CONCACAF Gold Cup`,
	`UEFA European Championship Qualifying`,
	`UEFA European Under-21 Championship`,
	`Copa America`,
	`Africa Cup of Nations qualifying`,
	`WAFU Cup of Nations`,
	`AFC Asian Cup Qualifiers`,
	`SAFF Championship`,
	`Men's Olympic Tournament`,
	`Women's International Friendly`,
	`FIFA Club World Cup`,
	`FIFA World Cup Qualifying - CONCACAF`,
	`FIFA World Cup Qualifying - CONMEBOL`,
	`FIFA World Cup Qualifying - CAF`,
	`FIFA Under-20 World Cup`,
	`International Friendly`,
	`CONCACAF Nations League Qualifying`,
	`UEFA European Championship`,
	`UEFA Nations League`,
	`UEFA European Under-19 Championship`,
	`Africa Cup of Nations`,
	`Africa Nations Championship`,
	`AFC Cup`,
	`AFF Cup`,
	`FIFA Women's World Cup`,
	`Women's Olympic Tournament`,
];
