
{
	"apiFootballID": "40",
	"name": "Liverpool",
	"logo": "https://media.api-sports.io/football/teams/40.png",
	"country": "England",
	"city": "Liverpool",
	"founded": 1892,
	"national": false,
	"allMatches": [
		{
			"api_football_id": 787056,
			"league": "League Cup",
			"league_id": 48,
			"season": 2021,
			"round": "3rd Round",
			"date": "2021-09-21T18:45:00+00:00",
			"referee": "D. England",
			"home": "Norwich",
			"home_id": 71,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 1,
			"ft_home": 0,
			"ft_away": 3,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:34.784Z"
		},
		{
			"api_football_id": 800359,
			"league": "League Cup",
			"league_id": 48,
			"season": 2021,
			"round": "Round of 16",
			"date": "2021-10-27T18:45:00+00:00",
			"referee": "D. Coote",
			"home": "Preston",
			"home_id": 59,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 0,
			"ft_home": 0,
			"ft_away": 2,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:34.790Z"
		},
		{
			"api_football_id": 810063,
			"league": "League Cup",
			"league_id": 48,
			"season": 2021,
			"round": "Quarter-finals",
			"date": "2021-12-21T00:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Leicester",
			"away_id": 46,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:34.791Z"
		},
		{
			"api_football_id": 710563,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 1",
			"date": "2021-08-14T16:30:00+00:00",
			"referee": "Andre Marriner, England",
			"home": "Norwich",
			"home_id": 71,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 1,
			"ft_home": 0,
			"ft_away": 3,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:41.381Z"
		},
		{
			"api_football_id": 710571,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 2",
			"date": "2021-08-21T11:30:00+00:00",
			"referee": "Mike Dean, England",
			"home": "Liverpool",
			"home_id": 40,
			"away": "Burnley",
			"away_id": 44,
			"ht_home": 1,
			"ht_away": 0,
			"ft_home": 2,
			"ft_away": 0,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": true,
			"away_win": false,
			"created_at": "2021-11-01T19:34:41.387Z"
		},
		{
			"api_football_id": 710579,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 3",
			"date": "2021-08-28T16:30:00+00:00",
			"referee": "Anthony Taylor, England",
			"home": "Liverpool",
			"home_id": 40,
			"away": "Chelsea",
			"away_id": 49,
			"ht_home": 1,
			"ht_away": 1,
			"ft_home": 1,
			"ft_away": 1,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.391Z"
		},
		{
			"api_football_id": 710591,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 4",
			"date": "2021-09-12T15:30:00+00:00",
			"referee": "Craig Pawson, England",
			"home": "Leeds",
			"home_id": 63,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 1,
			"ft_home": 0,
			"ft_away": 3,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:41.396Z"
		},
		{
			"api_football_id": 710599,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 5",
			"date": "2021-09-18T14:00:00+00:00",
			"referee": "Andy Madley, England",
			"home": "Liverpool",
			"home_id": 40,
			"away": "Crystal Palace",
			"away_id": 52,
			"ht_home": 1,
			"ht_away": 0,
			"ft_home": 3,
			"ft_away": 0,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": true,
			"away_win": false,
			"created_at": "2021-11-01T19:34:41.399Z"
		},
		{
			"api_football_id": 710607,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 6",
			"date": "2021-09-25T16:30:00+00:00",
			"referee": "Stuart Attwell, England",
			"home": "Brentford",
			"home_id": 55,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 1,
			"ht_away": 1,
			"ft_home": 3,
			"ft_away": 3,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.403Z"
		},
		{
			"api_football_id": 710621,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 7",
			"date": "2021-10-03T15:30:00+00:00",
			"referee": "Paul Tierney, England",
			"home": "Liverpool",
			"home_id": 40,
			"away": "Manchester City",
			"away_id": 50,
			"ht_home": 0,
			"ht_away": 0,
			"ft_home": 2,
			"ft_away": 2,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.408Z"
		},
		{
			"api_football_id": 710635,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 8",
			"date": "2021-10-16T11:30:00+00:00",
			"referee": "Jonathan Moss, England",
			"home": "Watford",
			"home_id": 38,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 2,
			"ft_home": 0,
			"ft_away": 5,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:41.414Z"
		},
		{
			"api_football_id": 710643,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 9",
			"date": "2021-10-24T15:30:00+00:00",
			"referee": "Anthony Taylor, England",
			"home": "Manchester United",
			"home_id": 33,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 4,
			"ft_home": 0,
			"ft_away": 5,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:41.417Z"
		},
		{
			"api_football_id": 710649,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 10",
			"date": "2021-10-30T14:00:00+00:00",
			"referee": "Mike Dean, England",
			"home": "Liverpool",
			"home_id": 40,
			"away": "Brighton",
			"away_id": 51,
			"ht_home": 2,
			"ht_away": 1,
			"ft_home": 2,
			"ft_away": 2,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.419Z"
		},
		{
			"api_football_id": 710665,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 11",
			"date": "2021-11-07T16:30:00+00:00",
			"referee": null,
			"home": "West Ham",
			"home_id": 48,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.425Z"
		},
		{
			"api_football_id": 710669,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 12",
			"date": "2021-11-20T17:30:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Arsenal",
			"away_id": 42,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.427Z"
		},
		{
			"api_football_id": 710683,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 13",
			"date": "2021-11-27T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Southampton",
			"away_id": 41,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.433Z"
		},
		{
			"api_football_id": 710687,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 14",
			"date": "2021-12-01T20:15:00+00:00",
			"referee": null,
			"home": "Everton",
			"home_id": 45,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.434Z"
		},
		{
			"api_football_id": 710705,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 15",
			"date": "2021-12-04T15:00:00+00:00",
			"referee": null,
			"home": "Wolves",
			"home_id": 39,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.441Z"
		},
		{
			"api_football_id": 710713,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 16",
			"date": "2021-12-11T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Aston Villa",
			"away_id": 66,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.446Z"
		},
		{
			"api_football_id": 710724,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 17",
			"date": "2021-12-16T20:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Newcastle",
			"away_id": 34,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.453Z"
		},
		{
			"api_football_id": 710732,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 18",
			"date": "2021-12-19T16:30:00+00:00",
			"referee": null,
			"home": "Tottenham",
			"home_id": 47,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.460Z"
		},
		{
			"api_football_id": 710739,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 19",
			"date": "2021-12-26T12:30:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Leeds",
			"away_id": 63,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.465Z"
		},
		{
			"api_football_id": 710752,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 20",
			"date": "2021-12-28T20:00:00+00:00",
			"referee": null,
			"home": "Leicester",
			"home_id": 46,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.474Z"
		},
		{
			"api_football_id": 710758,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 21",
			"date": "2022-01-02T16:30:00+00:00",
			"referee": null,
			"home": "Chelsea",
			"home_id": 49,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.476Z"
		},
		{
			"api_football_id": 710769,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 22",
			"date": "2022-01-15T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Brentford",
			"away_id": 55,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.481Z"
		},
		{
			"api_football_id": 710779,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 23",
			"date": "2022-01-22T15:00:00+00:00",
			"referee": null,
			"home": "Crystal Palace",
			"home_id": 52,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.485Z"
		},
		{
			"api_football_id": 710794,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 24",
			"date": "2022-02-09T20:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Leicester",
			"away_id": 46,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.491Z"
		},
		{
			"api_football_id": 710797,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 25",
			"date": "2022-02-12T15:00:00+00:00",
			"referee": null,
			"home": "Burnley",
			"home_id": 44,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.492Z"
		},
		{
			"api_football_id": 710811,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 26",
			"date": "2022-02-19T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Norwich",
			"away_id": 71,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.497Z"
		},
		{
			"api_football_id": 710816,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 27",
			"date": "2022-02-26T15:00:00+00:00",
			"referee": null,
			"home": "Arsenal",
			"home_id": 42,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.499Z"
		},
		{
			"api_football_id": 710829,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 28",
			"date": "2022-03-05T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "West Ham",
			"away_id": 48,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.504Z"
		},
		{
			"api_football_id": 710838,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 29",
			"date": "2022-03-12T15:00:00+00:00",
			"referee": null,
			"home": "Brighton",
			"home_id": 51,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.508Z"
		},
		{
			"api_football_id": 710849,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 30",
			"date": "2022-03-19T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Manchester United",
			"away_id": 33,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.512Z"
		},
		{
			"api_football_id": 710861,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 31",
			"date": "2022-04-02T14:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Watford",
			"away_id": 38,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.517Z"
		},
		{
			"api_football_id": 710871,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 32",
			"date": "2022-04-09T14:00:00+00:00",
			"referee": null,
			"home": "Manchester City",
			"home_id": 50,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.522Z"
		},
		{
			"api_football_id": 710876,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 33",
			"date": "2022-04-16T14:00:00+00:00",
			"referee": null,
			"home": "Aston Villa",
			"home_id": 66,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.523Z"
		},
		{
			"api_football_id": 710893,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 34",
			"date": "2022-04-23T14:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Everton",
			"away_id": 45,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.530Z"
		},
		{
			"api_football_id": 710900,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 35",
			"date": "2022-04-30T14:00:00+00:00",
			"referee": null,
			"home": "Newcastle",
			"home_id": 34,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.532Z"
		},
		{
			"api_football_id": 710913,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 36",
			"date": "2022-05-07T14:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Tottenham",
			"away_id": 47,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.538Z"
		},
		{
			"api_football_id": 710921,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 37",
			"date": "2022-05-15T14:00:00+00:00",
			"referee": null,
			"home": "Southampton",
			"home_id": 41,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.541Z"
		},
		{
			"api_football_id": 710933,
			"league": "Premier League",
			"league_id": 39,
			"season": 2021,
			"round": "Regular Season - 38",
			"date": "2022-05-22T15:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Wolves",
			"away_id": 39,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:41.546Z"
		},
		{
			"api_football_id": 787573,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 1",
			"date": "2021-09-15T19:00:00+00:00",
			"referee": "Szymon Marciniak, Poland",
			"home": "Liverpool",
			"home_id": 40,
			"away": "AC Milan",
			"away_id": 489,
			"ht_home": 1,
			"ht_away": 2,
			"ft_home": 3,
			"ft_away": 2,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": true,
			"away_win": false,
			"created_at": "2021-11-01T19:34:55.930Z"
		},
		{
			"api_football_id": 787580,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 2",
			"date": "2021-09-28T19:00:00+00:00",
			"referee": "Sergei Karasev, Russia",
			"home": "FC Porto",
			"home_id": 212,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 0,
			"ht_away": 2,
			"ft_home": 1,
			"ft_away": 5,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:55.933Z"
		},
		{
			"api_football_id": 787595,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 3",
			"date": "2021-10-19T19:00:00+00:00",
			"referee": "Daniel Siebert, Germany",
			"home": "Atletico Madrid",
			"home_id": 530,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": 2,
			"ht_away": 2,
			"ft_home": 2,
			"ft_away": 3,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": false,
			"away_win": true,
			"created_at": "2021-11-01T19:34:55.939Z"
		},
		{
			"api_football_id": 787620,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 4",
			"date": "2021-11-03T20:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "Atletico Madrid",
			"away_id": 530,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:55.948Z"
		},
		{
			"api_football_id": 787637,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 5",
			"date": "2021-11-24T20:00:00+00:00",
			"referee": null,
			"home": "Liverpool",
			"home_id": 40,
			"away": "FC Porto",
			"away_id": 212,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:55.956Z"
		},
		{
			"api_football_id": 787642,
			"league": "UEFA Champions League",
			"league_id": 2,
			"season": 2021,
			"round": "Group Stage - 6",
			"date": "2021-12-07T20:00:00+00:00",
			"referee": null,
			"home": "AC Milan",
			"home_id": 489,
			"away": "Liverpool",
			"away_id": 40,
			"ht_home": null,
			"ht_away": null,
			"ft_home": null,
			"ft_away": null,
			"et_home": null,
			"et_away": null,
			"pen_home": null,
			"pen_away": null,
			"home_win": null,
			"away_win": null,
			"created_at": "2021-11-01T19:34:55.959Z"
		}
	]
}