const COUNTRIES = [
  `Belgium`,
  `France`,
  `Brazil`,
  `England`,
  `Portugal`,
  `Spain`,
  `Argentina`,
  `Uruguay`,
  `Mexico`,
  `Italy`,
  `Croatia`,
  `Denmark`,
  `Germany`,
  `Netherlands`,
  `Colombia`,
  `Switzerland`,
  `Chile`,
  `Wales`,
  `Poland`,
  `Senegal`,
  `Sweden`,
  `USA`,
  `Austria`,
  `Ukraine`,
  `Peru`,
  `Tunisia`,
  `Japan`,
  `Venezuela`,
  `Iran`,
  `Serbia`,
  `Algeria`,
  `Turkey`,
  `Morocco`,
  `Slovakia`,
  `Paraguay`,
  `Nigeria`,
  `Romania`,
  `Korea Republic`,
  `Russia`,
  `Hungary`,
  `Australia`,
  `Republic of Ireland`,
  `Czech Republic`,
  `Norway`,
  `Northern Ireland`,
  `Iceland`,
  `Jamaica`,
  `Scotland`,
  `Egypt`,
  `Costa Rica`,
  `Cameroon`,
  `Ghana`,
  `Greece`,
  `Mali`,
  `Finland`,
  `Bosnia-Herzegovina`,
  `Ecuador`,
  `Qatar`,
  `Burkina Faso`,
  `Congo DR`,
  `Côte d'Ivoire`,
  `Slovenia`,
  `Montenegro`,
  `Honduras`,
  `North Macedonia`,
  `Albania`,
  `Saudi Arabia`,
  `Bulgaria`,
  `Iraq`,
  `El Salvador`,
  `South Africa`,
  `Guinea`,
  `Canada`,
  `UAE`,
  `China PR`,
  `Syria`,
  `Curaçao`,
  `Panama`,
  `Bolivia`,
  `Cape Verde Islands`,
  `Oman`,
  `Benin`,
  `Uganda`,
  `Haiti`,
  `Uzbekistan`,
  `Gabon`,
  `Israel`,
  `Belarus`,
  `Georgia`,
  `Congo`,
  `Zambia`,
  `Lebanon`,
  `Vietnam`,
  `Madagascar`,
  `Jordan`,
  `Kyrgyz Republic`,
  `Bahrain`,
  `Luxembourg`,
  `Armenia`,
  `Cyprus`,
  `Mauritania`,
  `Palestine`,
  `Trinidad and Tobago`,
  `Kenya`,
  `India`,
  `Mozambique`,
  `Faroe Islands`,
  `Azerbaijan`,
  `Estonia`,
  `Thailand`,
  `Libya`,
  `Zimbabwe`,
  `Niger`,
  `Central African Republic`,
  `Korea DPR`,
  `Sierra Leone`,
  `Kosovo`,
  `New Zealand`,
  `Guinea-Bissau`,
  `Tajikistan`,
  `Namibia`,
  `Kazakhstan`,
  `Malawi`,
  `Philippines`,
  `Angola`,
  `Antigua and Barbuda`,
  `Sudan`,
  `Togo`,
  `Lithuania`,
  `Guatemala`,
  `Comoros`,
  `Turkmenistan`,
  `Rwanda`,
  `Equatorial Guinea`,
  `Tanzania`,
  `Latvia`,
  `Myanmar`,
  `Burundi`,
  `Chinese Taipei`,
  `St. Kitts and Nevis`,
  `Suriname`,
  `Solomon Islands`,
  `Lesotho`,
  `Hong Kong`,
  `Yemen`,
  `Ethiopia`,
  `Botswana`,
  `Kuwait`,
  `Nicaragua`,
  `Afghanistan`,
  `Andorra`,
  `Liberia`,
  `Eswatini`,
  `Malaysia`,
  `Maldives`,
  `New Caledonia`,
  `Gambia`,
  `Singapore`,
  `Dominican Republic`,
  `Grenada`,
  `Tahiti`,
  `Barbados`,
  `South Sudan`,
  `Fiji`,
  `Vanuatu`,
  `Papua New Guinea`,
  `Guyana`,
  `St. Vincent / Grenadines`,
  `Bermuda`,
  `Belize`,
  `Nepal`,
  `Mauritius`,
  `Indonesia`,
  `Cambodia`,
  `St. Lucia`,
  `Malta`,
  `Moldova`,
  `Chad`,
  `Puerto Rico`,
  `Cuba`,
  `Liechtenstein`,
  `Macau`,
  `Montserrat`,
  `Djibouti`,
  `Dominica`,
  `Bangladesh`,
  `São Tomé e Príncipe`,
  `Laos`,
  `Bhutan`,
  `Mongolia`,
  `Brunei`,
  `American Samoa`,
  `Cayman Islands`,
  `Samoa`,
  `Gibraltar`,
  `Bahamas`,
  `Timor-Leste`,
  `Somalia`,
  `Guam`,
  `Pakistan`,
  `Aruba`,
  `Seychelles`,
  `Tonga`,
  `Turks and Caicos Islands`,
  `Eritrea`,
  `Sri Lanka`,
  `US Virgin Islands`,
  `British Virgin Islands`,
  `Anguilla`,
];

module.exports = COUNTRIES;
